package com.example.util

enum class Language {
    EN, TA
}

object LocalizedStrings {
    private val strings = mapOf(
        Language.EN to mapOf(
            "title" to "PaperBundle",
            "search_placeholder" to "Search notes...",
            "amma" to "Amma",
            "appa" to "Appa",
            "amma_bundle" to "Amma's Bundle",
            "appa_bundle" to "Appa's Bundle",
            "add_task" to "Write New Note...",
            "save" to "Hang Note 📌",
            "cancel" to "Keep Back",
            "enter_task_hint" to "Write task here... (e.g. Pay electricity bill, Buy milk)",
            "voice_hint" to "Or tap the microphone to speak!",
            "completed_title" to "Completed Notes 📋",
            "no_pending_amma" to "Amma's bundle is empty! Tap + to write a note.",
            "no_pending_appa" to "Appa's bundle is empty! Tap + to write a note.",
            "no_pending_member" to "%s's bundle is empty! Tap + to write a note.",
            "no_completed" to "No completed notes archived yet.",
            "delete_confirm" to "Throw away this note into the trash?",
            "delete_yes" to "Throw Away 🗑️",
            "delete_no" to "Keep It",
            "today" to "Today",
            "yesterday" to "Yesterday",
            "voice_not_supported" to "Voice recognizer is not available on this device.",
            "completed_label" to "Finished",
            "remaining_count" to "%d notes hanging",
            "remaining_count_singular" to "1 note hanging",
            "remaining_none" to "No notes hanging",
            "tamil_opt" to "தமிழ்",
            "english_opt" to "English",
            "voice_speech_not_understood" to "Could not understand. Please try speaking again.",
            "all_notes" to "All Notes",
            "sign_in_google" to "Continue with Google Sync",
            "app_desc" to "Your shared digital household notice board.",
            "choose_user_profile" to "Tap profile to emulate direct entry:",
            "create_family_title" to "Create Family Workspace",
            "create_family_desc" to "Register a new shared board for your family",
            "family_name_hint" to "Enter Household Name (e.g. Baskaran Home)",
            "create_button" to "Create Board 📝",
            "join_family_title" to "Join Family Board",
            "join_button" to "Join Board 🤝",
            "or_label" to "─ OR ─",
            "logout_button" to "Disconnect Shared Board",
            "family_info" to "Board: %s",
            "added_by" to "By %s",
            "completed_by" to "Done by %s"
        ),
        Language.TA to mapOf(
            "title" to "காகிதக்கட்டு",
            "search_placeholder" to "குறிப்புகளைத் தேடுக...",
            "amma" to "அம்மா",
            "appa" to "அப்பா",
            "amma_bundle" to "அம்மாவின் கட்டு",
            "appa_bundle" to "அப்பாவின் கட்டு",
            "add_task" to "புதிய குறிப்பு எழுதுக...",
            "save" to "குறிப்பை மாட்டு 📌",
            "cancel" to "மடக்கு",
            "enter_task_hint" to "குறிப்பை எழுதவும் (உதா: மின் கட்டணம் செலுத்தவும், பால் வாங்கவும்)",
            "voice_hint" to "அல்லது பேச மைக் பட்டனை அழுத்தவும்!",
            "completed_title" to "முடித்த குறிப்புகள் 📋",
            "no_pending_amma" to "அம்மாவின் குறிப்பு கட்டு காலியாக உள்ளது. எழுத + ஐ அழுத்தவும்.",
            "no_pending_appa" to "அப்பாவின் குறிப்பு கட்டு காலியாக உள்ளது. எழுத + ஐ அழுத்தவும்.",
            "no_pending_member" to "%s குறிப்பு கட்டு காலியாக உள்ளது. எழுத + ஐ அழுத்தவும்.",
            "no_completed" to "முடிக்கப்பட்ட குறிப்புகள் எதுவும் இல்லை.",
            "delete_confirm" to "இந்த குறிப்பை குப்பைத்தொட்டியில் போட வேண்டுமா?",
            "delete_yes" to "போடவும் 🗑️",
            "delete_no" to "வைத்துக் கொள்",
            "today" to "இன்று",
            "yesterday" to "நேற்று",
            "voice_not_supported" to "இந்த போனில் வாய்ஸ் டைப்பிங் வேலை செய்யவில்லை.",
            "completed_label" to "முடிந்தது",
            "remaining_count" to "%d குறிப்புகள் உள்ளன",
            "remaining_count_singular" to "1 குறிப்பு உள்ளது",
            "remaining_none" to "குறிப்புகள் ஏதுமில்லை",
            "tamil_opt" to "தமிழ்",
            "english_opt" to "English",
            "voice_speech_not_understood" to "பேசியது புரியவில்லை. மீண்டும் பேசவும்.",
            "all_notes" to "எல்லா குறிப்புகள்",
            "sign_in_google" to "கூகுள் மூலம் இணைக்கவும்",
            "app_desc" to "உங்கள் பகிர்வு குடும்ப டிஜிட்டல் அறிவிப்பு பலகை.",
            "choose_user_profile" to "உள்நுழைய உறுப்பினரைத் தேர்ந்தெடுக்கவும்:",
            "create_family_title" to "குடும்ப குழுவை உருவாக்கு",
            "create_family_desc" to "உங்கள் குடும்பத்திற்காக ஒரு பகிர்வு பலகையை தொடங்குங்கள்",
            "family_name_hint" to "குடும்பத்தின் பெயர் (உதா: பாஸ்கரன் இல்லம்)",
            "create_button" to "பலகையை உருவாக்கு 📝",
            "join_family_title" to "குடும்ப பலகையில் இணை",
            "join_button" to "பலகையில் இணை 🤝",
            "or_label" to "─ அல்லது ─",
            "logout_button" to "பகிர்வு பலகையை விலக்குக",
            "family_info" to "பலகை பெயர்: %s",
            "added_by" to "%s எழுதினார்",
            "completed_by" to "%s முடித்தார்"
        )
    )

    fun get(key: String, lang: Language): String {
        return strings[lang]?.get(key) ?: strings[Language.EN]?.get(key) ?: key
    }
}
